#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from math import factorial

filename = 'rosalind_pmch.txt'
with open(filename) as file_object:
    rna = file_object.read()
    
def matching(rna):
    return (factorial(rna.count("A"))*factorial(rna.count("G")))

print(matching(rna))
