#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#Given: A DNA string
#Return: The reverse complement

filename = 'rosalind_revc.txt'
       
with open(filename) as file_object:
    dna = file_object.read()

complements = {'A': 'T', 'C': 'G', 'T':'A', 'G':'C'}

def work_it(strand):  

    comple = ""

    for nucleotide in strand:
        comple += complements[nucleotide]
    
    return comple[::-1] #reverses list

print(work_it(dna))
